# Generated by Django 4.0.1 on 2022-02-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.IntegerField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, db_column='Technology', max_length=10, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, db_column='Years_of_experience', null=True)),
                ('last_used', models.CharField(blank=True, db_column='Last_used', max_length=10, null=True)),
                ('certified', models.IntegerField(blank=True, db_column='Certified', null=True)),
            ],
        ),
    ]
