# Generated by Django 4.0.1 on 2022-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('emp_id', models.CharField(db_column='Emp_id', max_length=10, primary_key=True, serialize=False)),
                ('effective_start_date', models.DateField(blank=True, db_column='Effective_start_date', null=True)),
                ('effective_end_date', models.DateField(blank=True, db_column='Effective_end_date', null=True)),
                ('last_updated_by', models.CharField(blank=True, db_column='Last_updated_by', max_length=10, null=True)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_updated_date', null=True)),
                ('hire_date', models.DateField(blank=True, db_column='Hire_date', null=True)),
                ('ok_to_rehire', models.CharField(blank=True, db_column='Ok_to_rehire', max_length=10, null=True)),
                ('termination_date', models.DateField(blank=True, db_column='Termination_date', null=True)),
                ('benefits_start_date', models.DateField(blank=True, db_column='Benefits_start_date', null=True)),
                ('benefits_end_date', models.DateField(blank=True, db_column='Benefits_end_date', null=True)),
                ('is_effective', models.IntegerField(blank=True, null=True)),
                ('total_years_of_experience', models.CharField(blank=True, db_column='Total_years_of_experience', max_length=10, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
            ],
        ),
    ]
