# Generated by Django 4.0.1 on 2022-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetable',
            name='benefits_end_date',
            field=models.DateField(blank=True, db_column='BenefitsEndDate', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='benefits_start_date',
            field=models.DateField(blank=True, db_column='BenefitsStartDate', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='effective_end_date',
            field=models.DateField(blank=True, db_column='EffectiveEndDate', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='effective_start_date',
            field=models.DateField(blank=True, db_column='EffectiveStartDate', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='emp_id',
            field=models.CharField(db_column='EmpId', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='hire_date',
            field=models.DateField(blank=True, db_column='HireDate', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='is_effective',
            field=models.IntegerField(blank=True, db_column='IsEffective', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='last_updated_by',
            field=models.CharField(blank=True, db_column='LastUpdatedBy', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='last_updated_date',
            field=models.DateField(blank=True, db_column='LastUpdatedDate', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='ok_to_rehire',
            field=models.CharField(blank=True, db_column='OkToRehire', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='termination_date',
            field=models.DateField(blank=True, db_column='TerminationDate', null=True),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='total_years_of_experience',
            field=models.CharField(blank=True, db_column='TotalYearsOfExperience', max_length=10, null=True),
        ),
    ]
