# Generated by Django 4.0.1 on 2022-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(blank=True, db_column='Organization_type', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=10, null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=10, null=True)),
                ('company_code', models.CharField(blank=True, db_column='Company_code', max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, db_column='Company_name', max_length=10, null=True)),
                ('account_code', models.CharField(blank=True, db_column='Account_code', max_length=10, null=True)),
                ('account_bt_name', models.CharField(blank=True, db_column='Account_bt_name', max_length=10, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=20, null=True)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=20, null=True)),
                ('address3', models.CharField(blank=True, db_column='Address3', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='Postal_code', max_length=10, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10, null=True)),
            ],
        ),
    ]
