# Generated by Django 4.0.1 on 2022-02-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoTable',
            fields=[
                ('first_name', models.CharField(db_column='First_name', max_length=10, primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, db_column='Last_name', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('intial', models.CharField(blank=True, db_column='Intial', max_length=5, null=True)),
                ('marital_status', models.CharField(blank=True, db_column='Marital_status', max_length=10, null=True)),
                ('ethnicity_code', models.CharField(blank=True, db_column='Ethnicity_code', max_length=10, null=True)),
                ('is_effective', models.IntegerField(blank=True, null=True)),
                ('effective_start_date', models.DateField(blank=True, db_column='Effective_start_date', null=True)),
                ('effective_end_date', models.DateField(blank=True, db_column='Effective_end_date', null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('last_updated_by', models.CharField(blank=True, db_column='Last_updated_by', max_length=10, null=True)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_updated_date', null=True)),
            ],
        ),
    ]
