# Generated by Django 4.0.1 on 2022-02-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=10, null=True)),
                ('mark_percentage', models.IntegerField(blank=True, db_column='Mark_percentage', null=True)),
                ('pass_out_year', models.CharField(blank=True, db_column='Pass_out_year', max_length=10, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=10, null=True)),
                ('institution_name', models.CharField(blank=True, db_column='Institution_name', max_length=10, null=True)),
            ],
        ),
    ]
