# Generated by Django 4.0.1 on 2022-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, db_column='Phone_no', max_length=10, null=True)),
                ('phone_type', models.CharField(blank=True, db_column='Phone_type', max_length=10, null=True)),
                ('country_code', models.CharField(blank=True, db_column='Country_code', max_length=10, null=True)),
                ('extension', models.CharField(blank=True, db_column='Extension', max_length=10, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('last_updated_by', models.CharField(blank=True, db_column='Last_updated_by', max_length=10, null=True)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_updated_date', null=True)),
                ('address_type', models.CharField(blank=True, db_column='Address_type', max_length=10, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='Postal_code', max_length=10, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=10, null=True)),
                ('is_effective', models.IntegerField(blank=True, null=True)),
                ('effective_start_date', models.DateField(blank=True, db_column='Effective_start_date', null=True)),
                ('effective_end_date', models.DateField(blank=True, db_column='Effective_end_date', null=True)),
            ],
        ),
    ]
