# Generated by Django 4.0.1 on 2022-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_flag', models.CharField(blank=True, db_column='Primary_flag', max_length=10, null=True)),
                ('relationship', models.CharField(blank=True, db_column='Relationship', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('last_updated_by', models.CharField(blank=True, db_column='Last_updated_by', max_length=10, null=True)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_updated_date', null=True)),
            ],
        ),
    ]
