# Generated by Django 4.0.1 on 2022-02-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_emp_id', models.CharField(blank=True, db_column='Manager_emp_id', max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, db_column='First_name', max_length=10, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_name', max_length=10, null=True)),
                ('work_phone', models.CharField(blank=True, db_column='Work_phone', max_length=10, null=True)),
                ('manager_email', models.CharField(blank=True, db_column='Manager_email', max_length=10, null=True)),
                ('is_effective', models.IntegerField(blank=True, null=True)),
                ('effective_start_date', models.DateField(blank=True, db_column='Effective_start_date', null=True)),
                ('effective_end_date', models.DateField(blank=True, db_column='Effective_end_date', null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('last_updated_by', models.CharField(blank=True, db_column='Last_updated_by', max_length=10, null=True)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_updated_date', null=True)),
            ],
        ),
    ]
