# Generated by Django 4.0.1 on 2022-02-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, db_column='National_id', max_length=10, null=True)),
                ('card_type', models.CharField(blank=True, db_column='Card_type', max_length=10, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('last_updated_by', models.CharField(blank=True, db_column='Last_updated_by', max_length=10, null=True)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_updated_date', null=True)),
            ],
        ),
    ]
