# Generated by Django 4.0.1 on 2022-02-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, db_column='Currency', max_length=10, null=True)),
                ('basic', models.IntegerField(blank=True, db_column='Basic', null=True)),
                ('dearness_allowance', models.IntegerField(blank=True, db_column='Dearness_allowance', null=True)),
                ('hra', models.IntegerField(blank=True, db_column='HRA', null=True)),
                ('conveyance_allowance', models.IntegerField(blank=True, db_column='Conveyance_allowance', null=True)),
                ('special_allowance', models.IntegerField(blank=True, db_column='Special_allowance', null=True)),
                ('salary_advance', models.IntegerField(blank=True, db_column='Salary_advance', null=True)),
                ('pf_employee', models.IntegerField(blank=True, db_column='PF_employee', null=True)),
                ('esic_employee', models.IntegerField(blank=True, db_column='ESIC_employee', null=True)),
                ('pt', models.IntegerField(blank=True, db_column='PT', null=True)),
                ('pf_employer_cont', models.IntegerField(blank=True, db_column='PF_employer_cont', null=True)),
                ('esic_employer_cont', models.IntegerField(blank=True, db_column='ESIC_employer_cont', null=True)),
                ('is_effective', models.IntegerField(blank=True, null=True)),
                ('effective_start_date', models.DateField(blank=True, db_column='Effective_start_date', null=True)),
                ('effective_end_date', models.DateField(blank=True, db_column='Effective_end_date', null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=10, null=True)),
                ('last_updated_by', models.CharField(blank=True, db_column='Last_updated_by', max_length=10, null=True)),
                ('last_updated_date', models.DateField(blank=True, db_column='Last_updated_date', null=True)),
            ],
        ),
    ]
