# Generated by Django 4.0.1 on 2022-02-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, db_column='Bank_name', max_length=10, null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, db_column='Account_number', max_length=10, null=True)),
                ('ifsc_code', models.CharField(blank=True, db_column='IFSC_code', max_length=10, null=True)),
                ('beneficiary_name', models.CharField(blank=True, db_column='Beneficiary_name', max_length=10, null=True)),
                ('account_type', models.CharField(blank=True, db_column='Account_type', max_length=10, null=True)),
                ('routing_number', models.CharField(blank=True, db_column='Routing_number', max_length=10, null=True)),
            ],
        ),
    ]
