# Generated by Django 4.0.1 on 2022-02-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEmployeetable',
            fields=[
                ('emp_id', models.CharField(db_column='Emp_id', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveProgressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, db_column='Year', max_length=10, null=True)),
                ('leave_balance', models.IntegerField(blank=True, db_column='Leave_balance', null=True)),
                ('leaves_availed', models.IntegerField(blank=True, db_column='Leaves_availed', null=True)),
                ('emp_id', models.ForeignKey(default='E0001', on_delete=django.db.models.deletion.RESTRICT, to='leave_progress.employeeemployeetable')),
            ],
        ),
    ]
